"""0925

Revision ID: c233e837573f
Revises: None
Create Date: 2016-09-25 10:41:39.041000

"""

# revision identifiers, used by Alembic.
revision = 'c233e837573f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
