"""10.4

Revision ID: c83c98ce6c59
Revises: 8855e2d30756
Create Date: 2016-10-26 10:36:49.755000

"""

# revision identifiers, used by Alembic.
revision = 'c83c98ce6c59'
down_revision = '8855e2d30756'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
